name: Action

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Pull code
        uses: actions/checkout@v3
      - name: publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: pages publish --project-name=flutter-repo
          workingDirectory: 'public'