name: Action

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Pull code
        uses: actions/checkout@v3
      - name: Install all requirement packages
        run: |
          sudo apt-get update
          sudo apt-get install wget xz-utils debsigs dpkg-dev
      - name: Pull Flutter SDK from official website
        run: |
          wget https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.0.5-stable.tar.xz
          tar -xf flutter_linux_3.0.5-stable.tar.xz
      - name: Build deb package
        run: |
          mv flutter debian/usr/share
          dpkg-deb --build debian
          mv debian.deb flutter_3.0.5-0_amd64.deb
          mv flutter_3.0.5-0_amd64.deb public
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          fingerprint: ${{ secrets.GPG_FINGERPRINT }}
      - name: Sign the deb file
        run: |
          debsigs --sign=TranqDart -k ${{ secrets.GPG_KEY_ID }} public/flutter_3.0.5-0_amd64.deb
      - name: Generate deb repository
        run: |
          dpkg-scanpackages ./public /dev/null > Release
          dpkg-scanpackages ./public /dev/null | gzip -9c > Packages.gz
      - name: rsync deployments to Sourceforge
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete
          path: public/
          remote_path: ${{ secrets.SF_PATH }}
          remote_host: web.sourceforge.net
          remote_user: ${{ secrets.SF_USERNAME }}
          remote_key: ${{ secrets.SF_PRIVATE_KEY }}
          remote_key_pass: ${{ secrets.SF_PASSWORD }}
